#---
#title: "plot pearson correlation of contig RCPM profiles"
#author: "Kate Mortensen"
#date: "5/10/2023"
#---

#---------Library Setup

library(optparse)
library(ggplot2)
library(latex2exp)


# Arguments------------------------

option_list = list(
  make_option(c("-i", "--input"), type="character", default=NULL, 
              help="/path/to/assembly2sp_count.tsv", metavar="character"),
  make_option(c("-o", "--outdir"), type="character", default=NULL, 
              help="path/to/output_directory", metavar="character"),
  make_option(c("-n", "--basename"), type="character", default=NULL, 
              help="basename of output file", metavar="character")
); 
 
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

# Variables------------------------------
input = opt$input
outdir = opt$outdir
basename = opt$basename
fig_height = 8
fig_width = 11

dir.create(outdir, showWarnings = FALSE)

# Test Variables--------------------------------

# input = "/home/kmorten/ADMB/DASTOOL_MAGS/results/assembly_rrcpm_pearson_pca_minimap.tsv"
# outdir = "/home/kmorten/ADMB/DASTOOL_MAGS/results/R_figs"
# basename = "assembly_rrcpm_pearson_pca_minimap"
# fig_height = 8
# fig_width = 11

# Contig Abundance RCPM Correlations -----------------

# input generated by profilingRCPM_V4.py
df <- read.csv(input, header=TRUE, sep = "\t")

# Base Plot -------------------------------------------

gg <- ggplot(df, aes(x=rrcpm_pearson_corr_pc1, y=rrcpm_pearson_corr_pc2, group=type)) 
gg <- gg + geom_point(aes(color=type)) + 
           labs(x='PC1', y='PC2', title='Contig Abundance Pearson Correlation')

# Shape -------------------------------------------------

# cols <- c("CRTabsent" = "gray90", 
#           "CRTpresent_outliers_removed" = "gold", 
#           "concensus" = "firebrick")

# gg <- gg + scale_color_manual(name="Contig Characterization", values=cols,
#               labels=unname(TeX(c("-crt, +outliers", "+crt, -outliers","consensus")))) 

cols <- c("CRTabsent" = "gray90", 
          "CRTpresent" = "gold", 
          "concensus" = "firebrick")

gg <- gg + scale_color_manual(name="Contig Characterization", values=cols,
              labels=unname(TeX(c("-crt", "+crt", "consensus")))) 

# Modify theme components -------------------------------------------

gg <- gg + theme(plot.title=element_text(size=20, 
                                    lineheight=1.2),  # title
            axis.title.x=element_text(size=15),  # X axis title
            axis.title.y=element_text(size=15),  # Y axis title
            axis.text.x=element_text(size=10),  # X axis text
            axis.text.y=element_text(size=10)) +  # Y axis text
            theme_minimal() +
            theme(aspect.ratio=1) + 
            facet_grid(~assembly)
            # facet_wrap(~ assembly, ncol=3, scales="free") 

# Modify Legend -------------------------------------------

gg <- gg + theme(legend.title=element_text(size=12),
            legend.justification=c("right", "bottom"), 
            legend.background = element_blank())

gg

ggsave(paste(basename, ".pdf", sep=""), gg, height=fig_height, width=fig_width, path = outdir, device = "pdf")
ggsave(paste(basename, ".png", sep=""), gg, height=fig_height, width=fig_width, path = outdir, device = "png")

